"""
PL_Azure_test_flow
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.providers.microsoft.azure.operators.adls import ADLSListOperator
import pendulum


default_args={
    "owner": "Siddhardha Madda,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-01-29", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Siddhardha Madda": "mailto:siddhardha.madda@acadiahealthcare.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrpl8m6r01hx01mp5w9ydyy9/cloud-ide/clrxr6ls1002u01kuqliasul6/clrz8s8ti00l301mooxbftnko",
    },
)
def PL_Azure_test_flow():
    adls_files = ADLSListOperator(
        path="https://acadiangdpadls.blob.core.windows.net/ngdp/ngdp_test.csv",
        azure_data_lake_conn_id="azureconn",
        task_id="adls_files",
    )

dag_obj = PL_Azure_test_flow()
