"""
PL_python_test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_test_print")
def python_test_print_func():
    print("Hello, this is for testing purpose")

default_args={
    "email_on_retry": True,
    "retries": 2,
    "owner": "Siddhardha Madda,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="10-20/5 10-11 * * *",
    start_date=pendulum.from_format("2024-02-09", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Siddhardha Madda": "mailto:siddhardha.madda@acadiahealthcare.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrpl8m6r01hx01mp5w9ydyy9/cloud-ide/clrxr6ls1002u01kuqliasul6/clserx0sw04pu01qjhhzj14qe",
    },
)
def PL_python_test():
    python_test_print = python_test_print_func()

dag_obj = PL_python_test()
