"""
PL_Simple_Print
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="print_hello")
def print_hello_func():
    print("Hello World - This is Acadia Health Care")

default_args={
    "owner": "Siddhardha Madda,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-02-26", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Siddhardha Madda": "mailto:siddhardha.madda@acadiahealthcare.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrpl8m6r01hx01mp5w9ydyy9/cloud-ide/clrxr6ls1002u01kuqliasul6/clt37co374f5d01n7bbiwjkau",
    },
)
def PL_Simple_Print():
    print_hello = print_hello_func()

dag_obj = PL_Simple_Print()
