"""
PL_Simple_Print
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.providers.microsoft.mssql.operators.mssql import MsSqlOperator
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="Print_Acadia")
def Print_Acadia_func():
    print("Hello World - This is Acadia Health Care")
    
    
    

@aql.dataframe(task_id="python_1")
def python_1_func():
    print("SQL Task Completed")

default_args={
    "owner": "Siddhardha Madda,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-02-26", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Siddhardha Madda": "mailto:siddhardha.madda@acadiahealthcare.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrpl8m6r01hx01mp5w9ydyy9/cloud-ide/clrxr6ls1002u01kuqliasul6/clt37co374f5d01n7bbiwjkau",
    },
)
def PL_Simple_Print():
    Print_Acadia = Print_Acadia_func()

    Azure_SQL_Operator_Check = MsSqlOperator(
        database="sqldb-AcadiaBI",
        sql="select * from [etl].[MedhostFacilities]",
        mssql_conn_id="AzureSQLWB",
        task_id="Azure_SQL_Operator_Check",
    )

    python_1 = python_1_func()

    Azure_SQL_Operator_Check << Print_Acadia

    python_1 << Azure_SQL_Operator_Check

dag_obj = PL_Simple_Print()
