"""
PL_WB_Test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
import pendulum
import textwrap


default_args={
    "owner": "William Brown,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-02-01", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "William Brown": "mailto:william.brown2@acadiahealthcare.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clrpl8m6r01hx01mp5w9ydyy9/cloud-ide/clrxr6ls1002u01kuqliasul6/cls3cszzx00kb01p5t4oryu4z",
    },
)
def PL_WB_Test():
    snowflake_proc_call_1 = SnowflakeOperator(
        sql="CALL ACADIA_DA_DB_DEV.ACADIA_EDW_STG.return_string_example();",
        snowflake_conn_id="snowflake_conn_test",
        task_id="snowflake_proc_call_1",
    )

    snowflake_copy_into_2 = SnowflakeOperator(
        sql=textwrap.dedent("""\
            Truncate Table ACADIA_DA_DB_DEV.ACADIA_EDW_STG.RISK_QUAL_PATIENT_INCIDENTS;
            
            COPY INTO ACADIA_DA_DB_DEV.ACADIA_EDW_STG.RISK_QUAL_PATIENT_INCIDENTS
            FROM ( Select 
            $1:HASFacilityCode::varchar,
            $1:FacilityName::varchar,
            $1:IncidentNumber::varchar,
            $1:RecordID::varchar,
            $1:IncidentDate::date,
            $1:ReportedDate::date,
            $1:AddDate::date,
            $1:IncidentTime::varchar,
            $1:PersonType::varchar,
            $1:IncType::varchar,
            $1:IncTypeDesc::varchar,
            $1:IncSubType::varchar,
            $1:IncSubTypeDesc::varchar,
            $1:RestraintType::varchar,
            $1:RestraintTypeDesc::varchar,
            $1:SevIndex::varchar,
            $1:AcadiaFacilityCode::varchar,
            $1:LevelofCare::varchar,
            $1:LevelOfCareDesc::varchar,
            $1:LocationCode::varchar,
            $1:LocationCodeDescription::varchar,
            $1:PrecautionCode::varchar,
            $1:PrecautionCodeDescription::varchar,
            try_to_date($1:LastModifiedDate::varchar,'dd/mm/yyyy')
            From @ACADIA_DA_DB_DEV.ACADIA_EDW_STG.ACADIA_ADLS_DEV/patient_incidents_2024-01-31.parquet) FILE_FORMAT = ACADIA_DA_DB_DEV.ACADIA_EDW_STG.acadia_parquet_format;"""),
        snowflake_conn_id="snowflake_conn_test",
        task_id="snowflake_copy_into_2",
    )

    snowflake_insert_3 = SnowflakeOperator(
        sql=textwrap.dedent("""\
            Truncate Table ACADIA_DA_DB_DEV.ACADIA_EDW_STG.TEST_DATA_1;
            
            insert into ACADIA_DA_DB_DEV.ACADIA_EDW_STG.TEST_DATA_1 (c_custkey,c_name) values ('10000002','TESTTEST');"""),
        snowflake_conn_id="snowflake_conn_test",
        task_id="snowflake_insert_3",
    )

    snowflake_copy_into_2 << snowflake_proc_call_1

    snowflake_insert_3 << snowflake_copy_into_2

dag_obj = PL_WB_Test()
